### ISSUE TITLE
Invullen en bespreken PSA tbv VNG

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-zaken#102]
Invullen format Project Start Architectuur (PSA) voor de MijnZaken service en vanuit Project Samenwerkende portalen voor de notificatie service. Mag in één PSA omdat we dit voor VIP samen laten vallen.

![Image](https://github.com/GemeenteNijmegen/mijn-zaken/assets/83816236/7d9f3f84-6092-4ec4-86a8-68c9084c2dd9)

Het document staat in de map DevOps - INTERN/VNG-MijnZaken en Portalen/VNG-MijnZaken/PSA

- [x] ontvangst document Den Haag van Paul Janssen
- [x] invullen PSA
- [ ] bespreken PSA met VNG

**Comment by wvdeeckhout** [comment]
@joostvanderborg wil je nog meelezen? Dank voor je reactie.

**Comment by joostvanderborg** [comment]
Doorgenomen, en behalve wat overbodige spaties niks aangepast. Lijkt me prima zo!

**Comment by wvdeeckhout** [comment]
Deze is verstuurd.
