### ISSUE TITLE
UItwerken statusinformatie voor bedrijven

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-zaken#206]
- stap 1: e-herkenninglogin checken, zodat Woweb geïnformeerd kan worden.

**Comment by joostvanderborg** [comment]
E-herkenning-login bevat kvk-nummer en RSIN (volgens test in testomgeving Signicat). Teruggekoppeld aan Woweb, betekent dat we vrij flexibel zijn.

**Comment by joostvanderborg** [comment]
VIP verwerkt KvK-nummer, dat is dus geen probleem. Wel is het zo dat het 'gemakkelijke' endpoint om op KVK zaken op te halen in de huidige versie van Open Zaak bij VIP nog niet draait. Er is mogelijk een workaround, maar updaten van open zaak heeft denk ik de voorkeur. Michel gaat een analyse maken van de impact van updaten.

**Comment by joostvanderborg** [comment]
Om dit werkend te krijgen:
- e-herkenning login op Mijn Nijmegen mogelijk maken
- Open zaak (Woweb) updaten om op KVK te kunnen zoeken (analyse wordt gedaan)
- Bevragen Open zaak op KVK mogelijk maken (in mijn-zaken)
Nieuwe epic van maken @wvdeeckhout ?
