### ISSUE TITLE
Khiem aanleveren wat huidige statussen bij zaaktypen zijn

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/mijn-zaken#219]

**Comment by joostvanderborg** [comment]
Gemaild, 

De mogelijke statussen:

-	Ontvangen
-	In behandeling
-	Zaak afgerond

En een paar zaaktypen hebben een variant:
-	Ontvangen
-	Zaakbehandeling gestart
-	In Behandeling
-	Zaak afgerond.
