### ISSUE TITLE
Overleggen met de afdeling over de optie van het tonen van zaken Mijn Nijmegen

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-zaken#74]
Met Rob Haans en mogelijk Frank Metzemaekers in gesprek over het tonen van de statusinformatie van JZ in Mijn Nijmegen. Onderzoeken wat de voor- en nadelen zijn.

**Comment by wvdeeckhout** [comment]
mailwisseling als onderlegger: 
<div style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Calibri; border-width: 1pt medium medium; border-style: solid none none; border-color: rgb(181, 196, 223) currentcolor currentcolor; border-image: none; padding: 3pt 0cm 0cm;"><p class="MsoNormal" style="margin: 0cm 0cm 12pt; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><b><span lang="NL" style="font-family: Calibri, sans-serif; color: black;">From:<span class="Apple-converted-space"> </span></span></b><span lang="NL" style="font-family: Calibri, sans-serif; color: black;">Frank Metzemaekers &lt;<a href="mailto:f.metzemaekers@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">f.metzemaekers@nijmegen.nl</a>&gt;<br><b>Date:<span class="Apple-converted-space"> </span></b>Monday, 24 July 2023 at 09:50<br><b>To:<span class="Apple-converted-space"> </span></b>Rob Haans &lt;<a href="mailto:r1.haans@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">r1.haans@nijmegen.nl</a>&gt;, Khiem Nguyen &lt;<a href="mailto:k.nguyen@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">k.nguyen@nijmegen.nl</a>&gt;,<span class="Apple-converted-space"> </span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">Joost</span></span><span class="Apple-converted-space"> </span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">van</span></span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">der</span></span><span class="Apple-converted-space"> </span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">Borg</span></span><span class="Apple-converted-space"> </span>&lt;<a href="mailto:j.van.der.borg@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">j.<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">van</span></span>.<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">der</span></span>.<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">borg</span></span>@nijmegen.nl</a>&gt;<br><b>Cc:<span class="Apple-converted-space"> </span></b>Mariska Baartman &lt;<a href="mailto:m.baartman@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">m.baartman@nijmegen.nl</a>&gt;, Wendy<span class="Apple-converted-space"> </span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">van</span></span><span class="Apple-converted-space"> </span>den Eeckhout &lt;<a href="mailto:w.van.den.eeckhout@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">w.<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">van</span></span>.den.eeckhout@nijmegen.nl</a>&gt;<br><b>Subject:<span class="Apple-converted-space"> </span></b>RE: Bekijken of JZ4all-zaken ook in Mijn Nijmegen kunnen</span><o:p></o:p></p></div><p class="MsoNormal" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0cm; font-family: &quot;Times New Roman&quot;, serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;">Dag Rob,<span class="Apple-converted-space"> </span></span><o:p></o:p></p><p class="MsoNormal" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0cm; font-family: &quot;Times New Roman&quot;, serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;"> </span><o:p></o:p></p><p class="MsoNormal" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0cm; font-family: &quot;Times New Roman&quot;, serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;">Op basis<span class="Apple-converted-space"> </span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">van</span></span><span class="Apple-converted-space"> </span>on<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">der</span></span>staande mailwisseling kan ik niet overzien wat hier nu precies aan me gevraagd wordt. Daar komt bij dat ik JZ per 1 september ga verlaten en het me belangrijker lijkt als de vraag wordt voorgelegd aan de blijvers. Victorien Vranken wordt hoofd JZ en tot half oktober is Jan de Roos nog naast haar aanwezig.</span><o:p></o:p></p><p class="MsoNormal" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0cm; font-family: &quot;Times New Roman&quot;, serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;"> </span><o:p></o:p></p><div style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Calibri;"><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><b><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;">Met vriendelijke groet,</span></b><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><b><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;">Frank Metzemaekers</span></b><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><b><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;"> </span></b><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;">Afdeling VJB</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;">Bureau Juridische Zaken</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;">Coördinator Rechtsbescherming</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;"><img width="195" height="89" id="Afbeelding_x0020_3" src="blob:https://github.com/4c982799-2e00-42e0-9939-11f2ffbd946c" alt="Image" tabindex="0" style="border: medium; width: 2.0312in; height: 0.927in;"></span><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><b><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;">Gemeente Nijmegen</span></b><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;">06 – 52780809</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><u><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;"><a href="mailto:f.metzemaekers@nijmegen.nl" title="mailto:f.metzemaekers@nijmegen.nl" style="color: rgb(0, 120, 215); text-decoration: underline;"><span style="color: blue;">f.metzemaekers@nijmegen.nl</span></a></span></u><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(127, 127, 127); line-height: 1.2;">bereikbaar op maandag t/m don<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">der</span></span>dag</span><o:p></o:p></p></div><p class="MsoNormal" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0cm; font-family: &quot;Times New Roman&quot;, serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125); line-height: 1.2;"> </span><o:p></o:p></p><div style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Calibri;"><div style="border-width: 1pt medium medium; border-style: solid none none; border-color: rgb(225, 225, 225) currentcolor currentcolor; border-image: none; padding: 3pt 0cm 0cm;"><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><b><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; line-height: 1.2;"><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">Van</span></span>:</span></b><span lang="NL" style="font-size: 11pt; font-family: Calibri, sans-serif; line-height: 1.2;"><span class="Apple-converted-space"> </span>Rob Haans &lt;<a href="mailto:r1.haans@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">r1.haans@nijmegen.nl</a>&gt;<span class="Apple-converted-space"> </span><br><b>Verzonden:</b><span class="Apple-converted-space"> </span>don<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">der</span></span>dag 20 juli 2023 13:23<br><b>Aan:</b><span class="Apple-converted-space"> </span>Khiem Nguyen &lt;<a href="mailto:k.nguyen@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">k.nguyen@nijmegen.nl</a>&gt;;<span class="Apple-converted-space"> </span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">Joost</span></span><span class="Apple-converted-space"> </span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">van</span></span><span class="Apple-converted-space"> </span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">der</span></span><span class="Apple-converted-space"> </span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">Borg</span></span><span class="Apple-converted-space"> </span>&lt;<a href="mailto:j.van.der.borg@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">j.<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">van</span></span>.<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">der</span></span>.<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">borg</span></span>@nijmegen.nl</a>&gt;; Frank Metzemaekers &lt;<a href="mailto:f.metzemaekers@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">f.metzemaekers@nijmegen.nl</a>&gt;<br><b>CC:</b><span class="Apple-converted-space"> </span>Mariska Baartman &lt;<a href="mailto:m.baartman@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">m.baartman@nijmegen.nl</a>&gt;; Wendy<span class="Apple-converted-space"> </span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">van</span></span><span class="Apple-converted-space"> </span>den Eeckhout &lt;<a href="mailto:w.van.den.eeckhout@nijmegen.nl" class="ms-outlook-linkify" style="text-decoration: underline; color: rgb(0, 120, 215) !important;">w.<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">van</span></span>.den.eeckhout@nijmegen.nl</a>&gt;<br><b>On<span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">der</span></span>werp:</b><span class="Apple-converted-space"> </span>Re: Bekijken of JZ4all-zaken ook in Mijn Nijmegen kunnen</span><o:p></o:p></p></div></div><p class="MsoNormal" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0cm; font-family: &quot;Times New Roman&quot;, serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span lang="NL"> </span><o:p></o:p></p><div style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Calibri;"><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-family: Calibri, sans-serif; color: black;">Hoi<span class="Apple-converted-space"> </span><span data-markjs="true" class="outlook-search-highlight"><span data-markjs="true" class="outlook-search-highlight">Joost</span></span>, </span><o:p></o:p></p></div><div style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Calibri;"><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-family: Calibri, sans-serif; color: black;"> </span><o:p></o:p></p></div><div style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Calibri;"><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-family: Calibri, sans-serif; color: black;">Het lastige is dat JZ4all bewaar en beroep-zaken bevat, die een relatie hebben met zaken die waarschijnlijk nog niet via mijn Nijmegen ontsloten kunnen worden. Geeft dat niet verwarring? Wat vind jij<span class="Apple-converted-space"> </span><span id="OWAAM932883"><span class="MentionStyle_mention__DQ5Xl" style="border-radius: 4px; cursor: pointer; padding: 0px 2px; text-decoration: none; color: rgb(45, 87, 153); background-color: rgb(225, 222, 220); touch-action: pan-y; -webkit-user-select: text; -webkit-user-drag: none;">@Frank Metzemaekers</span></span>? </span><o:p></o:p></p></div><div style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Calibri;"><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-family: Calibri, sans-serif; color: black;"> </span><o:p></o:p></p></div><div style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Calibri;"><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-family: Calibri, sans-serif; color: black;">Groetjes,</span><o:p></o:p></p></div><div style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33); font-family: Calibri;"><div><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span lang="NL" style="font-family: Calibri, sans-serif; color: black;"> </span><o:p></o:p></p></div><div id="Signature"><div><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>

Rob Haans
--


</div></div></div>From: Frank Metzemaekers <[f.metzemaekers@nijmegen.nl](mailto:f.metzemaekers@nijmegen.nl)>
Date: Monday, 24 July 2023 at 09:50
To: Rob Haans <[r1.haans@nijmegen.nl](mailto:r1.haans@nijmegen.nl)>, Khiem Nguyen <[k.nguyen@nijmegen.nl](mailto:k.nguyen@nijmegen.nl)>, Joost van der Borg <[j.van.der.borg@nijmegen.nl](mailto:j.van.der.borg@nijmegen.nl)>
Cc: Mariska Baartman <[m.baartman@nijmegen.nl](mailto:m.baartman@nijmegen.nl)>, Wendy van den Eeckhout <[w.van.den.eeckhout@nijmegen.nl](mailto:w.van.den.eeckhout@nijmegen.nl)>
Subject: RE: Bekijken of JZ4all-zaken ook in Mijn Nijmegen kunnen

Dag Rob,
 
Op basis van onderstaande mailwisseling kan ik niet overzien wat hier nu precies aan me gevraagd wordt. Daar komt bij dat ik JZ per 1 september ga verlaten en het me belangrijker lijkt als de vraag wordt voorgelegd aan de blijvers. Victorien Vranken wordt hoofd JZ en tot half oktober is Jan de Roos nog naast haar aanwezig.
 
Met vriendelijke groet,
Frank Metzemaekers
 
Afdeling VJB
Bureau Juridische Zaken
Coördinator Rechtsbescherming
 
Image
Gemeente Nijmegen
06 – 52780809
[f.metzemaekers@nijmegen.nl](mailto:f.metzemaekers@nijmegen.nl)
bereikbaar op maandag t/m donderdag
 
Van: Rob Haans <[r1.haans@nijmegen.nl](mailto:r1.haans@nijmegen.nl)> 
Verzonden: donderdag 20 juli 2023 13:23
Aan: Khiem Nguyen <[k.nguyen@nijmegen.nl](mailto:k.nguyen@nijmegen.nl)>; Joost van der Borg <[j.van.der.borg@nijmegen.nl](mailto:j.van.der.borg@nijmegen.nl)>; Frank Metzemaekers <[f.metzemaekers@nijmegen.nl](mailto:f.metzemaekers@nijmegen.nl)>
CC: Mariska Baartman <[m.baartman@nijmegen.nl](mailto:m.baartman@nijmegen.nl)>; Wendy van den Eeckhout <[w.van.den.eeckhout@nijmegen.nl](mailto:w.van.den.eeckhout@nijmegen.nl)>
Onderwerp: Re: Bekijken of JZ4all-zaken ook in Mijn Nijmegen kunnen
 
Hoi Joost, 
 
Het lastige is dat JZ4all bewaar en beroep-zaken bevat, die een relatie hebben met zaken die waarschijnlijk nog niet via mijn Nijmegen ontsloten kunnen worden. Geeft dat niet verwarring? Wat vind jij @Frank Metzemaekers? 
 
Groetjes,
 
Rob Haans

**Comment by joostvanderborg** [comment]
Contact opgenomen, wacht op reactie.

**Comment by wvdeeckhout** [comment]
@joostvanderborg , kan deze op gereed? Je hebt van Victorien vernomen dat ze eerst de afdeling wil verkennen en er daarna op terugkomen toch?

**Comment by joostvanderborg** [comment]
Klopt inderdaad.
